### ISSUE TITLE
ssh_broker does not seem to handle losing the connection very well

### ISSUE THREAD

**Issue by robert-eby** [att/gopkgs#8]
If an ssh connection dies (for example, the remote sshd process is killed or the remote machine crashes), then ssh_broker does not seem to notice this and does not start a new connection.  As a result, any new requests to that machine just fail.  I would expect the ssh_broker to notice the bad connection when a new request comes in for that machine, and attempt to re-establish the connection.

**Comment by ScottDaniels** [comment]
The bug has been fixed.  Ssh_broker now resets a connection if it is broken either because the remote sshd process failed or was killed, or the remote host rebooted.  The fix has been tested using test/debug_sshbroker and the following command:

debug_ssh_broker -k /home/me/.ssh/vmkey.pk -c 'sleep 10' -h some_vm -u vmuser -R 100 -d 50

This executes a sleep 10 on the remote host 100 times waiting 50 seconds after a response before issuing another command.  The remote VM can be rebooted either during the execution of the sleep, or during the delay; as soon as the VM restarts the next attempt should be successful; any attempts while the VM is booting up will result in unable to establish connection errors (expected).  If the reboot happens during the execution of the sleep command, then the debug process should report a connection broken error.     The broker was also tested by killing the remote sshd process, rather than booting the VM.   In this case the next attempt should be successful.

The change was also tested by supplying multiple hosts with the -h option.  The expected behavour in this case is for the commands to the host(s) that are not stopped to continue to operate normally, and the commands resuming on the booted VM when the VM has restarted.

Fixed in commit: bcdb55
